////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Connecting to an Elasticsearch cluster
include::_attributes.adoc[]
:summary: This guide covers how to interact with an Elasticsearch cluster using the low level REST client or the Elasticsearch Java client.
:topics: data,search,elasticsearch,nosql
:extensions: io.quarkus:quarkus-elasticsearch-java-client,io.quarkus:quarkus-elasticsearch-vertx-client

Elasticsearch is a well known full text search engine and NoSQL datastore.

In this guide, we will see how you can get your REST services to interact with an Elasticsearch cluster.

Quarkus provides two ways of accessing Elasticsearch:

* The lower level REST Client
* The Elasticsearch Java client

[WARNING]
====
A third Quarkus extension for the "high level REST Client" used to exist,
but was removed as this client has been deprecated by Elastic and has some licensing issues.
====

== Prerequisites

include::{includes}/prerequisites.adoc[]
* Elasticsearch installed or Docker installed

== Architecture

The application built in this guide is quite simple: the user can add elements in a list using a form and the list is updated.

All the information between the browser and the server is formatted as JSON.

The elements are stored in Elasticsearch.

== Creating the Maven project

First, we need a new project. Create a new project with the following command:

:create-app-artifact-id: elasticsearch-quickstart
:create-app-extensions: rest-jackson,elasticsearch-vertx-client
include::{includes}/devtools/create-app.adoc[]

This command generates a Maven structure importing the Quarkus REST (formerly RESTEasy Reactive), Jackson, and Elasticsearch low level REST client extensions.

The Elasticsearch low level REST client comes with the `quarkus-elasticsearch-vertx-client` extension
that has been added to your build file.

If you want to use the Elasticsearch Java client instead, replace the `quarkus-elasticsearch-vertx-client` extension by the `quarkus-elasticsearch-java-client` extension.

[NOTE]
====
We use the `rest-jackson` extension here and not the JSON-B variant because we will use the Vert.x `JsonObject` helper
to serialize/deserialize our objects to/from Elasticsearch and it uses Jackson under the hood.
====

To add the extensions to an existing project, follow the instructions below.

For the Elasticsearch low level REST client, add the following dependency to your build file:

[source,xml,role="primary asciidoc-tabs-target-sync-cli asciidoc-tabs-target-sync-maven"]
.pom.xml
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-elasticsearch-vertx-client</artifactId>
</dependency>
----

[source,gradle,role="secondary asciidoc-tabs-target-sync-gradle"]
.build.gradle
----
implementation("io.quarkus:quarkus-elasticsearch-vertx-client")
----

For the Elasticsearch Java client, add the following dependency to your build file:

[source,xml,role="primary asciidoc-tabs-target-sync-cli asciidoc-tabs-target-sync-maven"]
.pom.xml
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-elasticsearch-java-client</artifactId>
</dependency>
----

[source,gradle,role="secondary asciidoc-tabs-target-sync-gradle"]
.build.gradle
----
implementation("io.quarkus:quarkus-elasticsearch-java-client")
----

== Creating your first JSON REST service

In this example, we will create an application to manage a list of fruits.

First, let's create the `Fruit` bean as follows:

[source,java]
----
package org.acme.elasticsearch;

public class Fruit {
    public String id;
    public String name;
    public String color;
}
----

Nothing fancy. One important thing to note is that having a default constructor is required by the JSON serialization layer.

Now create a `org.acme.elasticsearch.FruitService` that will be the business layer of our application
and will store/load the fruits from the Elasticsearch instance.
Here we use the low level REST client, if you want to use the Java API client instead,
follow the instructions in the <<using-the-elasticsearch-java-client,Using the Elasticsearch Java Client>> paragraph instead.

[source,java]
----
package org.acme.elasticsearch;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

import io.quarkus.elasticsearch.restclient.vertx.Request;
import io.quarkus.elasticsearch.restclient.vertx.Response;
import io.quarkus.elasticsearch.restclient.vertx.VertxElasticsearchClient;

import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;

@ApplicationScoped
public class FruitService {
    @Inject
    VertxElasticsearchClient restClient; //<1>

    public void index(Fruit fruit) throws IOException {
        Request request = new Request(
                "PUT",
                "/fruits/_doc/" + fruit.id, Map.of(), //<2>
                Map.of("Content-Type", "application/json"),
                JsonObject.mapFrom(fruit).toBuffer(), null); //<3>
        restClient.performRequest(request); //<4>
    }

    public void index(List<Fruit> list) throws IOException {

        var entityList = new ArrayList<JsonObject>();

        for (var fruit : list) {

            entityList.add(new JsonObject().put("index", new JsonObject()//<5>
                    .put("_index", "fruits").put("_id", fruit.id)));
            entityList.add(JsonObject.mapFrom(fruit));
        }

        Buffer body = Buffer.buffer(toNdJsonString(entityList)); //<6>
        Request request = new Request(
                "POST", "/fruits/_bulk", Map.of("pretty", "true"),
                Map.of("Content-Type", "application/x-ndjson"), //<7>
                body, null);
        restClient.performRequest(request);
    }

    public void delete(List<String> identityList) throws IOException {

        var entityList = new ArrayList<JsonObject>();

        for (var id : identityList) {
            entityList.add(new JsonObject().put("delete",
                    new JsonObject().put("_index", "fruits").put("_id", id)));//<8>
        }

        Request request = new Request(
                "POST", "/fruits/_bulk", Map.of("pretty", "true"),
                Map.of("Content-Type", "application/x-ndjson"),
                Buffer.buffer(toNdJsonString(entityList)), null);
        restClient.performRequest(request);
    }

    public Fruit get(String id) throws IOException {
        Request request = new Request(
                "GET",
                "/fruits/_doc/" + id);
        Response response = restClient.performRequest(request);
        String responseBody = response.getBody().toString();
        JsonObject json = new JsonObject(responseBody); //<9>
        return json.getJsonObject("_source").mapTo(Fruit.class);
    }

    public List<Fruit> searchByColor(String color) throws IOException {
        return search("color", color);
    }

    public List<Fruit> searchByName(String name) throws IOException {
        return search("name", name);
    }

    private List<Fruit> search(String term, String match) throws IOException {
        //construct a JSON query like {"query": {"match": {"<term>": "<match"}}
        JsonObject termJson = new JsonObject().put(term, match);
        JsonObject matchJson = new JsonObject().put("match", termJson);
        JsonObject queryJson = new JsonObject().put("query", matchJson);
        Request request = new Request("GET", "/fruits/_search", Map.of(),
                Map.of("Content-Type", "application/json"), queryJson.toBuffer(), null);
        Response response = restClient.performRequest(request);
        String responseBody = response.getBody().toString();

        JsonObject json = new JsonObject(responseBody);
        JsonArray hits = json.getJsonObject("hits").getJsonArray("hits");
        List<Fruit> results = new ArrayList<>(hits.size());
        for (int i = 0; i < hits.size(); i++) {
            JsonObject hit = hits.getJsonObject(i);
            Fruit fruit = hit.getJsonObject("_source").mapTo(Fruit.class);
            results.add(fruit);
        }
        return results;
    }

    private static String toNdJsonString(List<JsonObject> objects) {
        return objects.stream()
                .map(JsonObject::encode)
                .collect(Collectors.joining("\n", "", "\n"));
    }    
}
----
<1> We inject an Elasticsearch low level `VertxElasticsearchClient` into our service.
<2> We create an Elasticsearch request.
<3> We use Vert.x `JsonObject` to serialize the object before sending it to Elasticsearch, you can use whatever you want to serialize your objects to JSON.
<4> We send the request (indexing request here) to Elasticsearch.
<5> As we `index` collection of objects we should use `index`, `create` or `update` action.
<6> We use `toNdJsonString(entityList)` call to produce output like below
+
[source, json]
----
{"index", {"_index" : "fruits", "_id", "1"}}
{"id": "1", "name": "apple", "color": "red"}
...           ...             ...        ...
{"create", {"_index" : "fruits", "_id", "N"}}
{"id": "N", "name": "dragonfruit", "color": "pink"}

----
<7> Pass the content type that is expected by the search backend for bulk requests.
<8> The bulk API's delete operation JSON already contains all the required information; hence, there is no request body following this operation in the Bulk API request body.
+
[source, json]
----
{"delete", {"_index" : "fruits", "_id", "1"}}
{"delete", {"_index" : "fruits", "_id", "2"}}
...           ...             ...        ...
{"delete", {"_index" : "fruits", "_id", "N"}}

----
<9> In order to deserialize the object from Elasticsearch, we again use Vert.x JsonObject.

Now, create the `org.acme.elasticsearch.FruitResource` class as follows:

[source,java]
----
package org.acme.elasticsearch;

import java.io.IOException;
import java.net.URI;
import java.util.List;
import java.util.UUID;

import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.BadRequestException;

@Path("/fruits")
public class FruitResource {

    @Inject
    FruitService fruitService;

    @POST
    public Response index(Fruit fruit) throws IOException {
        if (fruit.id == null) {
            fruit.id = UUID.randomUUID().toString();
        }
        fruitService.index(fruit);
        return Response.created(URI.create("/fruits/" + fruit.id)).build();
    }

    @Path("bulk")
    @DELETE
    public Response delete(List<String> identityList) throws IOException {
        fruitService.delete(identityList);
        return Response.ok().build();
    }

    @Path("bulk")
    @POST
    public Response index(List<Fruit> list) throws IOException {
        fruitService.index(list);
        return Response.ok().build();
    }

    @GET
    @Path("/{id}")
    public Fruit get(String id) throws IOException {
        return fruitService.get(id);
    }

    @GET
    @Path("/search")
    public List<Fruit> search(@RestQuery String name, @RestQuery String color) throws IOException {
        if (name != null) {
            return fruitService.searchByName(name);
        } else if (color != null) {
            return fruitService.searchByColor(color);
        } else {
            throw new BadRequestException("Should provide name or color query parameter");
        }
    }
}
----

The implementation is pretty straightforward and you just need to define your endpoints using the Jakarta REST annotations and use the `FruitService` to list/add new fruits.

== Configuring Elasticsearch
The main property to configure is the URL to connect to the Elasticsearch cluster.

For a typical clustered Elasticsearch service, a sample configuration would look like the following:

[source,properties]
----
# configure the Elasticsearch client for a cluster of two nodes
quarkus.elasticsearch.hosts = elasticsearch1:9200,elasticsearch2:9200
----

In our case, we are using a single instance running on localhost:

[source,properties]
----
# configure the Elasticsearch client for a single instance on localhost
quarkus.elasticsearch.hosts = localhost:9200
----

If you need a more advanced configuration, you can find the comprehensive list of supported configuration properties at the end of this guide.

[[dev-services]]
=== Dev Services

Quarkus supports a feature called Dev Services that allows you to start various containers without any config.
In the case of Elasticsearch, this support extends to the default Elasticsearch connection.
What that means practically is that, if you have not configured `quarkus.elasticsearch.hosts`, Quarkus will automatically
start an Elasticsearch container when running tests or dev mode, and automatically configure the connection.

When running the production version of the application, the Elasticsearch connection needs to be configured as usual,
so if you want to include a production database config in your `application.properties` and continue to use Dev Services
we recommend that you use the `%prod.` profile to define your Elasticsearch settings.

For more information you can read the xref:elasticsearch-dev-services.adoc[Dev Services for Elasticsearch guide].

=== Programmatically Configuring Elasticsearch

On top of the parametric configuration, you can also programmatically apply additional configuration to the client by implementing a `ElasticsearchClientConfigConfigurer` and annotating it with `ElasticsearchClientConfig`. You may provide multiple implementations and configuration provided by each implementation will be applied in a randomly ordered cascading manner.

For example, when accessing an Elasticsearch cluster that is set up for TLS on the HTTP layer, the client needs to trust the certificate that Elasticsearch is using. The following is an example of setting up the client to trust the CA that has signed the certificate that Elasticsearch is using, when that CA certificate is available in a PKCS#12 keystore.

[source,java]
----
import io.quarkus.elasticsearch.vertx.ElasticsearchClientConfig;
import io.quarkus.elasticsearch.vertx.ElasticsearchClientConfigConfigurer;
import io.quarkus.elasticsearch.restclient.vertx.VertxElasticsearchClientBuilder;
import io.vertx.core.http.HttpClientOptions;
import io.vertx.core.net.PfxOptions;

@ElasticsearchClientConfig
public class TrustStoreConfigurator implements ElasticsearchClientConfigConfigurer {
    @Override
    public void accept(VertxElasticsearchClientBuilder builder) {
        builder.setHttpClientOptions(new HttpClientOptions().setTrustOptions(new PfxOptions()
                .setPath("/path/to/truststore.p12")
                .setPassword("password-for-keystore")));
    }
}
----

`setHttpClientOptions` replaces the HTTP client options built from the `quarkus.elasticsearch.*` configuration.
Include any configured settings you still need in the supplied `HttpClientOptions`.

Set `quarkus.elasticsearch.protocol=https` to enable TLS. Certificate and hostname verification remain enabled.

[NOTE]
====
Classes marked with `@ElasticsearchClientConfig` are made application scoped CDI beans by default.
You can override the scope at the class level if you prefer a different scope.
====

== Running an Elasticsearch cluster

As by default, the Elasticsearch client is configured to access a local Elasticsearch cluster on port 9200 (the default Elasticsearch port),
if you have a local running instance on this port, there is nothing more to do before being able to test it!

If you want to use Docker to run an Elasticsearch instance, you can use the following command to launch one:

[source,bash,subs=attributes+]
----
docker run --name elasticsearch  -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms512m -Xmx512m"\
       -e "cluster.routing.allocation.disk.threshold_enabled=false" -e "xpack.security.enabled=false"\
       --rm -p 9200:9200 {elasticsearch-image}
----

== Running the application

Let's start our application in dev mode:

include::{includes}/devtools/dev.adoc[]

You can add new fruits to the list via the following curl command:

[source,bash,subs=attributes+]
----
curl localhost:8080/fruits -d '{"name": "bananas", "color": "yellow"}' -H "Content-Type: application/json"
----

And search for fruits by name or color via the following curl command:

[source,bash,subs=attributes+]
----
curl localhost:8080/fruits/search?color=yellow
----

== Using the Elasticsearch Java Client

Here is a version of the `FruitService` using the Elasticsearch Java Client instead of the low level one:

[source,java]
----
import java.io.IOException;
import java.io.StringReader;
import java.util.List;
import java.util.stream.Collectors;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

import co.elastic.clients.elasticsearch.ElasticsearchClient;
import co.elastic.clients.elasticsearch.core.IndexRequest;
import co.elastic.clients.elasticsearch._types.FieldValue;
import co.elastic.clients.elasticsearch._types.query_dsl.QueryBuilders;
import co.elastic.clients.elasticsearch.core.search.Hit;
import co.elastic.clients.elasticsearch.core.search.HitsMetadata;
import co.elastic.clients.elasticsearch.core.GetRequest;
import co.elastic.clients.elasticsearch.core.GetResponse;
import co.elastic.clients.elasticsearch.core.SearchRequest;
import co.elastic.clients.elasticsearch.core.SearchResponse;
import co.elastic.clients.elasticsearch.core.BulkRequest;
import co.elastic.clients.elasticsearch.core.BulkResponse;

@ApplicationScoped
public class FruitService {
    @Inject
    ElasticsearchClient client; // <1>

    public void index(Fruit fruit) throws IOException {
        IndexRequest<Fruit> request = IndexRequest.of(  // <2>
            b -> b.index("fruits")
                .id(fruit.id)
                .document(fruit)); // <3>
        client.index(request);  // <4>
    }

    public void index(List<Fruit> list) throws IOException {

        BulkRequest.Builder br = new BulkRequest.Builder();

        for (var fruit : list) {
            br.operations(op -> op
                    .index(idx -> idx.index("fruits").id(fruit.id).document(fruit)));
        }

        BulkResponse result = client.bulk(br.build());

        if (result.errors()) {
            throw new RuntimeException("The indexing operation encountered errors.");
        }
    }

    public void delete(List<String> list) throws IOException {

        BulkRequest.Builder br = new BulkRequest.Builder();

        for (var id : list) {
            br.operations(op -> op.delete(idx -> idx.index("fruits").id(id)));
        }

        BulkResponse result = client.bulk(br.build());

        if (result.errors()) {
            throw new RuntimeException("The indexing operation encountered errors.");
        }
    }

    public Fruit get(String id) throws IOException {
        GetRequest getRequest = GetRequest.of(
            b -> b.index("fruits")
                .id(id));
        GetResponse<Fruit> getResponse = client.get(getRequest, Fruit.class);
        if (getResponse.found()) {
            return getResponse.source();
        }
        return null;
    }

    public List<Fruit> searchByColor(String color) throws IOException {
        return search("color", color);
    }

    public List<Fruit> searchByName(String name) throws IOException {
        return search("name", name);
    }

    private List<Fruit> search(String term, String match) throws IOException {
        SearchRequest searchRequest = SearchRequest.of(
            b -> b.index("fruits")
                .query(QueryBuilders.match().field(term).query(FieldValue.of(match)).build()._toQuery()));

        SearchResponse<Fruit> searchResponse = client.search(searchRequest, Fruit.class);
        HitsMetadata<Fruit> hits = searchResponse.hits();
        return hits.hits().stream().map(hit -> hit.source()).collect(Collectors.toList());
    }
}
----
<1> We inject an `ElasticsearchClient` inside the service.
<2> We create an Elasticsearch index request using a builder.
<3> We directly pass the object to the request as the Java API client has a serialization layer.
<4> We send the request to Elasticsearch.

== Hibernate Search Elasticsearch

Quarkus supports Hibernate Search with Elasticsearch via the `quarkus-hibernate-search-orm-elasticsearch` extension.

Hibernate Search Elasticsearch allows to synchronize your Jakarta Persistence entities to an Elasticsearch cluster and offers a way to query your Elasticsearch cluster using the Hibernate Search API.

If you are interested in it, please consult the xref:hibernate-search-orm-elasticsearch.adoc[Hibernate Search with Elasticsearch guide].

== Cluster Health Check

If you are using the `quarkus-smallrye-health` extension, both extensions will automatically add a readiness health check
to validate the health of the cluster.

So when you access the `/q/health/ready` endpoint of your application, you will have information about the cluster status.
It uses the cluster health endpoint, the check will be down if the status of the cluster is **red**, or the cluster is not available.

This behavior can be disabled by setting the `quarkus.elasticsearch.health.enabled` property to `false` in your `application.properties`.

== Building a native executable

You can use both clients in a native executable.

You can build a native executable with the usual command:

include::{includes}/devtools/build-native.adoc[]

Running it is as simple as executing `./target/elasticsearch-low-level-client-quickstart-1.0.0-SNAPSHOT-runner`.

You can then point your browser to `http://localhost:8080/fruits.html` and use your application.

== Conclusion

Accessing an Elasticsearch cluster from the low level REST client or the Elasticsearch Java client is easy with Quarkus as it provides easy configuration, CDI integration and native support for it.

// TODO: move to migration notes instead
== Migrating from the Apache REST client

Replace `io.quarkus:quarkus-elasticsearch-rest-client` with `io.quarkus:quarkus-elasticsearch-vertx-client`.
Inject `io.quarkus.elasticsearch.restclient.vertx.VertxElasticsearchClient` instead of `Rest5Client`.
Use the Vert.x client's `Request` type with a `Buffer` body, and read responses through `Response.getBody()`.
Request headers are mutable and use a case-insensitive Vert.x `MultiMap`. Do not modify them while a request is in flight.
Headers supplied on a request replace client default headers of the same name; otherwise the defaults are used.
Blocking `performRequest` calls must run on worker threads; use `performRequestAsync` on event-loop threads.
The extension owns the client lifecycle, so application code must not close the injected client.

The Elasticsearch Java client uses this transport automatically.
Injection of `ElasticsearchClient` and `ElasticsearchAsyncClient` is unchanged.
Move customizers to `io.quarkus.elasticsearch.vertx.ElasticsearchClientConfig` and
`ElasticsearchClientConfigConfigurer`, and customize `VertxElasticsearchClientBuilder` instead of the Apache builder.

The following properties use Vert.x terminology. All names have the `quarkus.elasticsearch.` prefix:

[cols="1,1,1"]
|===
|Deprecated alias |Replacement |Default
|`connection-timeout` |`connect-timeout` |`1S`
|`socket-timeout` |`read-idle-timeout` |`30S`
|`max-connections-per-route` |`http1-max-pool-size` |`20`
|===

Deprecated aliases remain supported. Values from higher-priority configuration sources take precedence;
when priorities match, the replacement name wins. Defaults apply when neither name is configured.
`connect-timeout` limits connection establishment, while `read-idle-timeout` limits how long a connection can go without receiving data.
`http1-max-pool-size` limits HTTP/1 connections per server.

`max-connections` and `io-thread-counts` have been removed.
Size pools with `http1-max-pool-size`; there is no equivalent total-connection setting.
The client shares Quarkus-managed Vert.x threads: use `quarkus.vertx.event-loops-pool-size` when tuning that shared pool.

The Vert.x and Java client extensions no longer require Apache HTTP Components.
Hibernate Search currently retains its Apache transport and its separate per-backend configuration.
Applications also using Hibernate Search can therefore still contain Apache dependencies.

== Configuration Reference

include::{generated-dir}/config/quarkus-elasticsearch-vertx-client.adoc[opts=optional, leveloffset=+1]
