<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>quarkus-extensions-parent</artifactId>
        <groupId>io.quarkus</groupId>
        <version>999-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>quarkus-hibernate-search-standalone-elasticsearch-parent</artifactId>
    <name>Quarkus - Hibernate Search - Standalone + Elasticsearch</name>
    <packaging>pom</packaging>
    <modules>
        <module>deployment</module>
        <module>runtime</module>
        <module>runtime-dev</module>
    </modules>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>ban-apache-elasticsearch-transports</id>
                        <goals><goal>enforce</goal></goals>
                        <configuration>
                            <rules>
                                <bannedDependencies>
                                    <searchTransitive>true</searchTransitive>
                                    <excludes>
                                        <exclude>org.apache.httpcomponents:*</exclude>
                                        <exclude>org.apache.httpcomponents.client5:*</exclude>
                                        <exclude>org.apache.httpcomponents.core5:*</exclude>
                                        <exclude>org.elasticsearch.client:elasticsearch-rest*</exclude>
                                        <exclude>co.elastic.clients:elasticsearch-rest*</exclude>
                                        <exclude>org.hibernate.search:hibernate-search-backend-elasticsearch-client-rest*</exclude>
                                    </excludes>
                                    <includes>
                                        <include>*:*:*:*:test</include>
                                    </includes>
                                    <message>Hibernate Search Elasticsearch applications must use the Vert.x transport.</message>
                                </bannedDependencies>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
